<?php
// /frontend/includes/auth_scripts.php
// Handles decoding Google JWT and sending it to our backend
?>
<script>
    // Decode JWT token generated by Google
    function parseJwt(token) {
        var base64Url = token.split('.')[1];
        var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        var jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));
        return JSON.parse(jsonPayload);
    }

    // Google Callback Function
    function handleCredentialResponse(response) {
        // Decode the payload to get user info
        const responsePayload = parseJwt(response.credential);
        
        console.log("ID: " + responsePayload.sub);
        console.log('Full Name: ' + responsePayload.name);
        console.log('Email: ' + responsePayload.email);

        // Send to our PHP Backend Auth API
        fetch('<?= API_URL ?>/auth.php', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                google_id: responsePayload.sub,
                email: responsePayload.email,
                name: responsePayload.name
            })
        })
        .then(res => res.json())
        .then(data => {
            if(data.status === 'success') {
                // Reload page to reflect session state
                window.location.reload();
            } else {
                alert("Authentication Failed: " + data.message);
            }
        })
        .catch(err => console.error("Auth Error:", err));
    }
</script>