<?php
// /frontend/games/nodematch.php
// Premium CSS-Animated Memory Grid - V2 (With Overlays)
?>
<div class="flex flex-col items-center w-full max-w-md mx-auto relative z-10 h-full">
    <div class="flex justify-between w-full mb-4 font-mono text-xs uppercase tracking-widest text-gray-400 px-2">
        <div>Matches: <span id="nm-matches" class="text-premium-gold font-bold">0/8</span></div>
        <div>Moves: <span id="nm-moves" class="text-white font-bold">0</span></div>
    </div>
    
    <div class="relative w-full aspect-square">
        <!-- Game Board -->
        <div class="grid grid-cols-4 gap-2 sm:gap-3 bg-premium-panel/80 p-3 sm:p-4 rounded-3xl border border-gray-700/50 shadow-2xl w-full h-full perspective-1000" id="nm-board">
            <!-- Cards generated by JS -->
        </div>

        <!-- Premium Interactive Overlay -->
        <div id="nm-overlay" class="absolute inset-0 bg-black/85 flex flex-col items-center justify-center rounded-3xl z-20 backdrop-blur-md border border-gray-800/50 shadow-2xl transition-all duration-300">
            <div class="w-16 h-16 bg-gradient-to-br from-[#d4af37] to-[#aa8c2c] rounded-2xl flex items-center justify-center mb-6 shadow-lg shadow-premium-gold/20 border border-premium-gold/50">
                <i data-lucide="cpu" class="text-premium-dark w-8 h-8"></i>
            </div>
            <h2 class="text-2xl sm:text-3xl font-black text-white mb-2 tracking-widest uppercase text-center drop-shadow-md">Node Match</h2>
            <p class="text-gray-400 mb-8 text-xs sm:text-sm text-center max-w-[80%] leading-relaxed font-sans">Find cryptographic pairs. Fewer moves yield higher asset extraction.</p>
            <button onclick="startNMGame()" class="bg-premium-silver text-premium-dark px-8 py-4 rounded-xl font-bold tracking-widest active:scale-95 shadow-xl hover:bg-white transition-all text-xs uppercase flex items-center gap-2">
                <i data-lucide="unlock" size="16"></i> Initialize Decryption
            </button>
        </div>
    </div>
</div>

<style>
    .nm-card { position: relative; width: 100%; height: 100%; transform-style: preserve-3d; transition: transform 0.6s cubic-bezier(0.4, 0, 0.2, 1); cursor: pointer; }
    .nm-card.flipped { transform: rotateY(180deg); }
    .nm-face { position: absolute; width: 100%; height: 100%; backface-visibility: hidden; border-radius: 1rem; display: flex; align-items: center; justify-content: center; }
    .nm-front { background: #151518; border: 1px solid #333; transform: rotateY(0deg); transition: all 0.3s; }
    .nm-front:hover { background: #1f1f2e; border-color: #d4af37; box-shadow: inset 0 0 15px rgba(212,175,55,0.1); }
    .nm-back { background: #0a0a0c; border: 1px solid #d4af37; transform: rotateY(180deg); box-shadow: inset 0 0 20px rgba(212,175,55,0.2); }
    .nm-matched { opacity: 0.4; filter: grayscale(100%); transform: rotateY(180deg) scale(0.95); transition: all 0.5s ease-out; cursor: default; }
</style>

<script>
    const icons = ['cpu', 'database', 'shield', 'zap', 'wifi', 'terminal', 'server', 'radio'];
    let cards = [...icons, ...icons]; // Duplicate for pairs
    let flippedCards = [];
    let matchedCount = 0;
    let moves = 0;
    let nmActive = false;

    function shuffle(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    }

    function initNM() {
        shuffle(cards);
        const board = document.getElementById('nm-board');
        board.innerHTML = '';
        matchedCount = 0; moves = 0; nmActive = true;
        document.getElementById('nm-matches').innerText = '0/8';
        document.getElementById('nm-moves').innerText = '0';

        cards.forEach((icon, index) => {
            const cardEl = document.createElement('div');
            cardEl.className = 'nm-card';
            cardEl.dataset.icon = icon;
            cardEl.dataset.index = index;
            
            cardEl.innerHTML = `
                <div class="nm-face nm-front"><i data-lucide="fingerprint" class="text-gray-700 w-6 h-6"></i></div>
                <div class="nm-face nm-back"><i data-lucide="${icon}" class="text-premium-gold w-8 h-8 drop-shadow-[0_0_8px_rgba(212,175,55,0.5)]"></i></div>
            `;
            
            // Prevent 300ms mobile delay
            cardEl.addEventListener('pointerdown', (e) => { e.preventDefault(); flipCard(cardEl); });
            board.appendChild(cardEl);
        });
        lucide.createIcons();
    }

    function startNMGame() {
        document.getElementById('nm-overlay').classList.add('hidden');
        initNM();
    }

    function flipCard(card) {
        if(!nmActive || !gameLoopActive || flippedCards.length >= 2 || card.classList.contains('flipped') || card.classList.contains('nm-matched')) return;
        
        card.classList.add('flipped');
        flippedCards.push(card);

        if(flippedCards.length === 2) {
            moves++;
            document.getElementById('nm-moves').innerText = moves;
            nmActive = false; // block clicks
            
            setTimeout(checkMatch, 800);
        }
    }

    function checkMatch() {
        const [card1, card2] = flippedCards;
        if(card1.dataset.icon === card2.dataset.icon) {
            // Match
            matchedCount++;
            document.getElementById('nm-matches').innerText = `${matchedCount}/8`;
            
            card1.classList.add('nm-matched');
            card2.classList.add('nm-matched');
            
            if(matchedCount === 8) {
                // Win Delay
                setTimeout(() => endNMGame(), 600);
            } else {
                nmActive = true;
            }
        } else {
            // No Match
            card1.classList.remove('flipped');
            card2.classList.remove('flipped');
            nmActive = true;
        }
        flippedCards = [];
    }

    function endNMGame() {
        nmActive = false;
        const reward = Math.max(1000, 10000 - (moves * 150));
        
        const overlay = document.getElementById('nm-overlay');
        overlay.classList.remove('hidden');
        overlay.innerHTML = `
            <div class="w-16 h-16 bg-green-900/30 border border-green-500 rounded-2xl flex items-center justify-center mb-6 shadow-inner shadow-green-500/20">
                <i data-lucide="check-circle" class="text-green-500 w-8 h-8"></i>
            </div>
            <h2 class="text-2xl sm:text-3xl font-black text-white mb-2 uppercase tracking-widest text-center">Decryption Complete</h2>
            <div class="flex flex-col items-center gap-2 mb-8 bg-black/50 p-4 rounded-xl border border-gray-800 w-3/4">
                <p class="text-gray-400 font-mono text-xs uppercase tracking-widest">Moves: <span class="text-white">${moves}</span></p>
                <p class="text-premium-gold font-mono font-bold text-sm uppercase tracking-widest drop-shadow-md">Yield: +${reward} Assets</p>
            </div>
            <button onclick="startNMGame()" class="bg-premium-silver text-premium-dark px-8 py-4 rounded-xl font-bold tracking-widest active:scale-95 shadow-xl hover:bg-white transition-all text-xs uppercase flex items-center gap-2">
                <i data-lucide="refresh-cw" size="16"></i> Re-Initialize
            </button>
        `;
        lucide.createIcons();

        if(reward > 0) {
            fetch('<?= defined("API_URL") ? API_URL : "/api" ?>/wallet.php', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({action: 'game_win', amount: reward}) });
        }
    }

    // Initial render sets up icons but doesn't start logic until user clicks Initialize
    document.getElementById('nm-board').innerHTML = '<div class="col-span-4 flex items-center justify-center h-full text-gray-600 font-mono text-xs tracking-widest">AWAITING INITIALIZATION...</div>';
</script>