<?php
// /frontend/games/tictactoe.php
// Version 2: CSS Glitch effects & Mobile Fluidity
?>
<div class="flex flex-col items-center w-full max-w-sm mx-auto">
    <div id="ttt-status" class="mb-6 text-lg font-mono text-neon-cyan tracking-widest uppercase h-6">Awaiting input...</div>
    
    <div class="grid grid-cols-3 gap-2 sm:gap-3 bg-gray-900/50 p-3 sm:p-4 rounded-2xl border border-gray-800 shadow-[0_0_30px_rgba(0,0,0,0.5)] w-full aspect-square" id="ttt-board">
        <!-- Cells generated by JS -->
    </div>
    
    <button onclick="resetTTT()" class="mt-8 bg-gray-900 border border-gray-700 text-gray-300 px-8 py-3 rounded-xl hover:bg-white hover:text-black hover:border-white transition-all font-mono text-sm tracking-widest active:scale-95 shadow-lg">
        Reboot Grid
    </button>
</div>

<style>
    .ttt-cell { transition: all 0.2s; touch-action: manipulation; }
    .ttt-cell:active { transform: scale(0.95); }
    
    /* System Glitch Animation for AI */
    @keyframes aiGlitch {
        0% { transform: translate(0); text-shadow: -2px 0 red, 2px 0 blue; filter: invert(0); }
        20% { transform: translate(-2px, 1px); text-shadow: 2px 0 red, -2px 0 blue; filter: invert(0.2); }
        40% { transform: translate(2px, -1px); filter: invert(0.8); }
        60% { transform: translate(-1px, 2px); text-shadow: -2px 0 blue, 2px 0 red; filter: invert(0); }
        80% { transform: translate(1px, -2px); }
        100% { transform: translate(0); text-shadow: 0 0 10px #b026ff; }
    }
    .glitch-anim { animation: aiGlitch 0.4s ease-out; }
</style>

<script>
    let tttBoard = Array(9).fill(null);
    let tttActive = true;
    const baseReward = <?= isset($gameInfo['base_reward']) ? $gameInfo['base_reward'] : 5000 ?>;

    function initTTT() {
        const boardDiv = document.getElementById('ttt-board');
        boardDiv.innerHTML = '';
        for(let i=0; i<9; i++) {
            const cell = document.createElement('div');
            cell.className = 'ttt-cell bg-black border border-gray-800/80 rounded-xl flex items-center justify-center text-4xl sm:text-5xl cursor-pointer hover:border-neon-cyan/50 hover:bg-neon-cyan/5';
            cell.addEventListener('pointerdown', (e) => { e.preventDefault(); makeTTTMove(i); });
            boardDiv.appendChild(cell);
        }
    }

    function makeTTTMove(index) {
        if(tttBoard[index] || !tttActive || !gameLoopActive) return;
        
        tttBoard[index] = 'X';
        updateTTTUI();
        
        if(checkTTTWin('X')) { handleTTTEnd('VICTORY', baseReward); return; }
        if(tttBoard.every(c => c)) { handleTTTEnd('DRAW', baseReward / 2); return; }

        tttActive = false;
        const status = document.getElementById('ttt-status');
        status.innerText = "AI Processing...";
        status.classList.add('text-neon-purple');
        status.classList.remove('text-neon-cyan');
        
        // Board shake effect
        document.getElementById('ttt-board').classList.add('animate-pulse');

        setTimeout(() => {
            if(!gameLoopActive) return;
            document.getElementById('ttt-board').classList.remove('animate-pulse');
            
            let empty = tttBoard.map((v, i) => v === null ? i : null).filter(v => v !== null);
            // Smarter AI (Blocks player if needed, otherwise random)
            let aiMove = getBestMove() ?? empty[Math.floor(Math.random() * empty.length)];
            
            tttBoard[aiMove] = 'O';
            updateTTTUI(aiMove); // Pass the index to glitch it
            
            if(checkTTTWin('O')) { handleTTTEnd('SYSTEM FAILURE', 0); }
            else if(tttBoard.every(c => c)) { handleTTTEnd('DRAW', baseReward / 2); }
            else {
                tttActive = true;
                status.innerText = "Awaiting input...";
                status.classList.remove('text-neon-purple');
                status.classList.add('text-neon-cyan');
            }
        }, 600);
    }

    function getBestMove() {
        // Very basic block check
        const wins = [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]];
        for(let comb of wins) {
            let xCount = 0; let emptyIdx = null;
            for(let i of comb) {
                if(tttBoard[i] === 'X') xCount++;
                else if(tttBoard[i] === null) emptyIdx = i;
            }
            if(xCount === 2 && emptyIdx !== null) return emptyIdx; // Block!
        }
        return null;
    }

    function updateTTTUI(glitchIndex = -1) {
        const cells = document.getElementById('ttt-board').children;
        board.forEach((val, i) => {
            if(val === 'X' && cells[i].innerHTML === '') {
                cells[i].innerHTML = `<span class="text-neon-cyan drop-shadow-[0_0_10px_#00f0ff] font-bold">X</span>`;
                cells[i].classList.add('shadow-[inset_0_0_20px_rgba(0,240,255,0.2)]', 'border-neon-cyan/50');
            }
            if(val === 'O' && cells[i].innerHTML === '') {
                cells[i].innerHTML = `<span class="text-neon-purple drop-shadow-[0_0_10px_#b026ff] font-bold ${i === glitchIndex ? 'glitch-anim' : ''}">O</span>`;
                cells[i].classList.add('shadow-[inset_0_0_20px_rgba(176,38,255,0.2)]', 'border-neon-purple/50');
            }
        });
    }

    function checkTTTWin(player) {
        const wins = [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]];
        return wins.some(comb => comb.every(i => tttBoard[i] === player));
    }

    function handleTTTEnd(msg, reward) {
        tttActive = false;
        document.getElementById('ttt-status').innerText = msg;
        if(reward > 0) {
            fetch('<?= defined("API_URL") ? API_URL : "/api" ?>/wallet.php', { method: 'POST', body: JSON.stringify({action: 'game_win', amount: reward}) })
            .then(() => { document.getElementById('ttt-status').innerText += ` [+${reward}]`; });
        }
    }

    function resetTTT() {
        tttBoard = Array(9).fill(null);
        tttActive = true;
        const status = document.getElementById('ttt-status');
        status.innerText = "Awaiting input...";
        status.classList.remove('text-neon-purple', 'text-red-500');
        status.classList.add('text-neon-cyan');
        initTTT();
    }

    initTTT();
</script>