<?php
// /frontend/games/tictactoe.php
// Pure isolated logic for Quantum Tic-Tac-Toe
// Assumes it is included inside play.php
?>
<div class="flex flex-col items-center w-full">
    <div id="ttt-status" class="mb-6 text-xl font-mono text-neon-cyan">Awaiting your move...</div>
    
    <div class="grid grid-cols-3 gap-3 bg-gray-900 p-3 rounded-xl border border-gray-800" id="ttt-board">
        <!-- Cells generated by JS -->
    </div>
    
    <button onclick="resetTTT()" class="mt-8 border border-neon-cyan text-neon-cyan px-6 py-2 rounded hover:bg-neon-cyan/20 transition font-mono">
        Reboot Grid
    </button>
</div>

<script>
    let tttBoard = Array(9).fill(null);
    let tttActive = true;
    const baseReward = <?= $gameInfo['base_reward'] ?>;

    function initTTT() {
        const boardDiv = document.getElementById('ttt-board');
        boardDiv.innerHTML = '';
        for(let i=0; i<9; i++) {
            const cell = document.createElement('div');
            cell.className = 'w-24 h-24 bg-black border border-gray-700 flex items-center justify-center text-5xl cursor-pointer hover:bg-gray-800 transition rounded';
            cell.onclick = () => makeTTTMove(i);
            boardDiv.appendChild(cell);
        }
    }

    function makeTTTMove(index) {
        if(tttBoard[index] || !tttActive || !gameLoopActive) return; // Prevent move if ad is playing
        
        tttBoard[index] = 'X';
        updateTTTUI();
        
        if(checkTTTWin('X')) { handleTTTEnd('VICTORY', baseReward); return; }
        if(tttBoard.every(c => c)) { handleTTTEnd('DRAW', baseReward / 2); return; }

        tttActive = false;
        document.getElementById('ttt-status').innerText = "AI Processing...";
        
        setTimeout(() => {
            if(!gameLoopActive) return; // Don't move if paused
            let empty = tttBoard.map((v, i) => v === null ? i : null).filter(v => v !== null);
            let aiMove = empty[Math.floor(Math.random() * empty.length)];
            tttBoard[aiMove] = 'O';
            updateTTTUI();
            
            if(checkTTTWin('O')) { handleTTTEnd('SYSTEM FAILURE (Loss)', 0); }
            else if(tttBoard.every(c => c)) { handleTTTEnd('DRAW', baseReward / 2); }
            else {
                tttActive = true;
                document.getElementById('ttt-status').innerText = "Your Turn";
            }
        }, 800);
    }

    function updateTTTUI() {
        const cells = document.getElementById('ttt-board').children;
        tttBoard.forEach((val, i) => {
            if(val === 'X') cells[i].innerHTML = `<span class="text-neon-cyan drop-shadow-[0_0_8px_#00f0ff] font-bold">X</span>`;
            if(val === 'O') cells[i].innerHTML = `<span class="text-neon-purple drop-shadow-[0_0_8px_#b026ff] font-bold">O</span>`;
        });
    }

    function checkTTTWin(player) {
        const wins = [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]];
        return wins.some(comb => comb.every(i => tttBoard[i] === player));
    }

    function handleTTTEnd(msg, reward) {
        tttActive = false;
        document.getElementById('ttt-status').innerText = msg;
        if(reward > 0) {
            // Reward API Call
            fetch('<?= API_URL ?>/wallet.php', {
                method: 'POST', body: JSON.stringify({action: 'game_win', amount: reward})
            }).then(() => {
                document.getElementById('ttt-status').innerText += ` [+${reward} Coins]`;
            });
        }
    }

    function resetTTT() {
        tttBoard = Array(9).fill(null);
        tttActive = true;
        document.getElementById('ttt-status').innerText = "Awaiting your move...";
        initTTT();
    }

    // Start
    initTTT();
</script>